version: '3.6'
services:
  api:
    build: .
    image: gm-api
    restart: always
    command: >
      bash -c "npm install
      && npm run dev"
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - node-modules:/usr/src/node_modules
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: gamemaster
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
volumes:
  mongo-data:
    name: gamemaster-mongo-data

